interests:
  - History
  - Aviation
  - Engineering
  - Anthropology
  - Politics
  - Pop Culture
  - Economy
  - Architecture
  - Geography
  - Geology
  - Fauna
  - Flora
  - Myths
  - Mysteries

avoid:
  - Demographics
  - Administrative units
  - Changes in administrative boundaries
